// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Zirpl.Examples.Commerce.CodeGeneration._templates.ModelProject
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using Zirpl.AppEngine.VisualStudioAutomation;
    using Zirpl.AppEngine.VisualStudioAutomation.AppGeneration;
    using Zirpl.AppEngine.VisualStudioAutomation.AppGeneration.Config;
    using Zirpl.AppEngine.VisualStudioAutomation.TextTemplating;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\projects\ZAppEngine\Zirpl.Examples.Commerce.CodeGeneration\_templates\ModelProject\ModelExtensions_cs.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class ModelExtensions_cs : Zirpl.AppEngine.VisualStudioAutomation.AppGeneration.TextTemplating.OncePerAppTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Linq;\r\nusing Zirpl" +
                    ".AppEngine.Model;\r\nusing Zirpl.AppEngine.Model.Extensibility;\r\nusing Zirpl.Colle" +
                    "ctions;\r\n\r\nnamespace ");
            
            #line 17 "E:\projects\ZAppEngine\Zirpl.Examples.Commerce.CodeGeneration\_templates\ModelProject\ModelExtensions_cs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(App.ModelProject.GetDefaultNamespace()));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic static partial class ModelExtensions\r\n\t{\r\n");
            
            #line 21 "E:\projects\ZAppEngine\Zirpl.Examples.Commerce.CodeGeneration\_templates\ModelProject\ModelExtensions_cs.tt"

	foreach (var domainType in this.App.DomainTypes.Where(o => o.IsPersistable && (o.IsUpdatable || o.IsInsertable)))
	{

            
            #line default
            #line hidden
            this.Write("\t\tpublic static void Save(this ");
            
            #line 25 "E:\projects\ZAppEngine\Zirpl.Examples.Commerce.CodeGeneration\_templates\ModelProject\ModelExtensions_cs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(domainType.Name));
            
            #line default
            #line hidden
            this.Write(" entity)\r\n\t\t{\r\n\t\t}\r\n");
            
            #line 28 "E:\projects\ZAppEngine\Zirpl.Examples.Commerce.CodeGeneration\_templates\ModelProject\ModelExtensions_cs.tt"
	
    }
	foreach (var domainType in this.App.DomainTypes.Where(o => o.IsPersistable && (o.IsDeletable || o.IsMarkDeletable)))
	{

            
            #line default
            #line hidden
            this.Write("\t\tpublic static void Delete(this ");
            
            #line 33 "E:\projects\ZAppEngine\Zirpl.Examples.Commerce.CodeGeneration\_templates\ModelProject\ModelExtensions_cs.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(domainType.Name));
            
            #line default
            #line hidden
            this.Write(" entity)\r\n\t\t{\r\n\t\t}\r\n");
            
            #line 36 "E:\projects\ZAppEngine\Zirpl.Examples.Commerce.CodeGeneration\_templates\ModelProject\ModelExtensions_cs.tt"
	
    }

            
            #line default
            #line hidden
            this.Write("\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
