// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Zirpl.AppEngine.VisualStudioAutomation.AppGeneration._templates.ModelProject
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using Zirpl.AppEngine.VisualStudioAutomation;
    using Zirpl.AppEngine.VisualStudioAutomation.AppGeneration;
    using Zirpl.AppEngine.VisualStudioAutomation.AppGeneration.Config;
    using Zirpl.AppEngine.VisualStudioAutomation.TextTemplating;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class DT_Enum_cs : Zirpl.AppEngine.VisualStudioAutomation.AppGeneration.TextTemplating.OncePerDomainTypeTemplate
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Linq;\r\nusing Zirpl" +
                    ".AppEngine.Model;\r\nusing Zirpl.AppEngine.Model.Extensibility;\r\nusing Zirpl.Colle" +
                    "ctions;\r\n\r\nnamespace ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DomainType.Namespace));
            this.Write("\r\n{\r\n\tpublic enum ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DomainType.Name));
            this.Write("Enum : ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DomainType.IdProperty.DataTypeString));
            this.Write("\r\n\t{\r\n");

		foreach (var enumValue in this.DomainType.EnumValues)
		{

            this.Write("\t\t");
            this.Write(this.ToStringHelper.ToStringWithCulture(enumValue.Name));
            this.Write(" = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(enumValue.Id));
            this.Write(",\r\n");
	
		}

            this.Write("\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }

public override bool ShouldTransform { get { return this.DomainType.IsStaticLookup && this.DomainType.EnumValues.Any(); } }

    }
}
