// Generated helper templates
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Notifications\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\AppTransform.txt4
// Generated items
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionStatusTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionPeriodTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\StateProvinceTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\DiscountApplicabilityTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\DiscountAmountTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralCouponRequestStatusTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\SubscriptionOrderItemTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderStatusTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderChargeStatusTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\DiscountUsageRestrictionTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeStatusTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeMethodTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Notifications\EmailEventTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\NameSuffixTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\NamePrefixTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\TagMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionStatusTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionPeriodTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionPeriodMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionInstanceMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\PendingSubscriptionChangeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\TaxRuleMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\SystemSettingMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\StateProvinceTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\ReferralMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\PromoCodeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\DiscountApplicabilityTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\DiscountAmountTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\DiscountMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralPlanMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralCouponRequestStatusTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralCouponRequestMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\SubscriptionOrderItemTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\SubscriptionOrderItemMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\StripeCustomerChargeOptionMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\StripeChargeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ShoppingCartItemMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderStatusTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderItemMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderChargeStatusTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\DiscountUsageRestrictionTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\DiscountUsageMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeStatusTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeMethodTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Notifications\EmailEventTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Notifications\EmailEventMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\NameSuffixTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\NamePrefixTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\VisitorMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\PasswordResetLinkMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerTagMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerReferralMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerChargeOptionMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\TierShipmentMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\TierPriceMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\SubscriptionChoiceTierPriceCombinationMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\SubscriptionChoiceMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\ProductReviewMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\DisplayProductMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\CategoryMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\BrandMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\AddressMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Tag.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionStatusType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionPeriodType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionPeriod.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionInstance.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\Subscription.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\PendingSubscriptionChange.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\TaxRule.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\SystemSetting.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\StateProvinceType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\Referral.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\PromoCode.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\DiscountApplicabilityType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\DiscountAmountType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\Discount.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralPlan.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralCouponRequestStatusType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralCouponRequest.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferral.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\Partner.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\SubscriptionOrderItemType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\SubscriptionOrderItem.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\StripeCustomerChargeOption.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\StripeCharge.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ShoppingCartItem.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderStatusType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderItem.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderChargeStatusType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\Order.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\DiscountUsageRestrictionType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\DiscountUsage.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeStatusType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeMethodType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\Charge.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Notifications\EmailEventType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Notifications\EmailEvent.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\NameSuffixType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\NamePrefixType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\Visitor.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\PasswordResetLink.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerTag.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerReferral.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerChargeOption.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\Customer.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\TierShipment.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\TierPrice.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\SubscriptionChoiceTierPriceCombination.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\SubscriptionChoice.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\ProductReview.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\DisplayProduct.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\Category.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\Brand.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Address.auto.cs
