// Generated helper templates
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Settings\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Promotions\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Partners\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Notifications\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Membership\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Customers\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Notifications\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\AppTransform.txt4
// Generated items
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\TagMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\SubscriptionStatusTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\SubscriptionPeriodTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\SubscriptionPeriodMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\SubscriptionInstanceMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\SubscriptionMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\PendingSubscriptionChangeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\TaxRuleMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\SystemSettingMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\StateProvinceTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\ReferralMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\PromoCodeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\DiscountApplicabilityTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\DiscountAmountTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\DiscountMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\PartnerReferralPlanMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\PartnerReferralCouponRequestStatusTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\PartnerReferralCouponRequestMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\PartnerReferralMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\PartnerMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\SubscriptionOrderItemTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\SubscriptionOrderItemMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\StripeCustomerChargeOptionMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\StripeChargeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\ShoppingCartItemMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\OrderStatusTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\OrderItemMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\OrderChargeStatusTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\OrderMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\DiscountUsageRestrictionTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\DiscountUsageMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\ChargeTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\ChargeStatusTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\ChargeMethodTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\ChargeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\EmailEventTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\EmailEventMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\NameSuffixTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\NamePrefixTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\VisitorMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\PasswordResetLinkMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\CustomerTagMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\CustomerReferralMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\CustomerChargeOptionMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\CustomerMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\TierShipmentMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\TierPriceMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\SubscriptionChoiceTierPriceCombinationMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\SubscriptionChoiceMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\ProductReviewMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\DisplayProductMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\CategoryMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\BrandMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\AddressMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\CommerceDataContext.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\TagDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\SubscriptionStatusTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\SubscriptionPeriodTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\SubscriptionPeriodDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\SubscriptionInstanceDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\SubscriptionDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\PendingSubscriptionChangeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Settings\TaxRuleDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Settings\SystemSettingDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Settings\StateProvinceTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Promotions\ReferralDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Promotions\PromoCodeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Promotions\DiscountApplicabilityTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Promotions\DiscountAmountTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Promotions\DiscountDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Partners\PartnerReferralPlanDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Partners\PartnerReferralCouponRequestStatusTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Partners\PartnerReferralCouponRequestDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Partners\PartnerReferralDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Partners\PartnerDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\SubscriptionOrderItemTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\SubscriptionOrderItemDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\StripeCustomerChargeOptionDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\StripeChargeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\ShoppingCartItemDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\OrderStatusTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\OrderItemDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\OrderChargeStatusTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\OrderDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\DiscountUsageRestrictionTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\DiscountUsageDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\ChargeTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\ChargeStatusTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\ChargeMethodTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\ChargeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Notifications\EmailEventTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Notifications\EmailEventDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\NameSuffixTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\NamePrefixTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Membership\VisitorDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Membership\PasswordResetLinkDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Customers\CustomerTagDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Customers\CustomerReferralDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Customers\CustomerChargeOptionDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Customers\CustomerDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\TierShipmentDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\TierPriceDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\SubscriptionChoiceTierPriceCombinationDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\SubscriptionChoiceDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\ProductReviewDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\DisplayProductDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\CategoryDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\BrandDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\AddressDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\ITagDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\ISubscriptionStatusTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\ISubscriptionPeriodTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\ISubscriptionPeriodDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\ISubscriptionInstanceDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\ISubscriptionDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\IPendingSubscriptionChangeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Settings\ITaxRuleDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Settings\ISystemSettingDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Settings\IStateProvinceTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Promotions\IReferralDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Promotions\IPromoCodeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Promotions\IDiscountApplicabilityTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Promotions\IDiscountAmountTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Promotions\IDiscountDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Partners\IPartnerReferralPlanDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Partners\IPartnerReferralCouponRequestStatusTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Partners\IPartnerReferralCouponRequestDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Partners\IPartnerReferralDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Partners\IPartnerDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\ISubscriptionOrderItemTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\ISubscriptionOrderItemDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IStripeCustomerChargeOptionDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IStripeChargeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IShoppingCartItemDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IOrderStatusTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IOrderItemDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IOrderChargeStatusTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IOrderDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IDiscountUsageRestrictionTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IDiscountUsageDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IChargeTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IChargeStatusTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IChargeMethodTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IChargeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Notifications\IEmailEventTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Notifications\IEmailEventDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\INameSuffixTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\INamePrefixTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Membership\IVisitorDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Membership\IPasswordResetLinkDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Customers\ICustomerTagDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Customers\ICustomerReferralDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Customers\ICustomerChargeOptionDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Customers\ICustomerDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\ITierShipmentDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\ITierPriceDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\ISubscriptionChoiceTierPriceCombinationDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\ISubscriptionChoiceDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\IProductReviewDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\IDisplayProductDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\ICategoryDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\IBrandDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\IAddressDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionStatusTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionPeriodTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\StateProvinceTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\DiscountApplicabilityTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\DiscountAmountTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralCouponRequestStatusTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\SubscriptionOrderItemTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderStatusTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderChargeStatusTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\DiscountUsageRestrictionTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeStatusTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeMethodTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Notifications\EmailEventTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\NameSuffixTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\NamePrefixTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\TagMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionStatusTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionPeriodTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionPeriodMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionInstanceMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\PendingSubscriptionChangeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\TaxRuleMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\SystemSettingMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\StateProvinceTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\ReferralMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\PromoCodeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\DiscountApplicabilityTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\DiscountAmountTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\DiscountMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralPlanMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralCouponRequestStatusTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralCouponRequestMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\SubscriptionOrderItemTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\SubscriptionOrderItemMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\StripeCustomerChargeOptionMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\StripeChargeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ShoppingCartItemMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderStatusTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderItemMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderChargeStatusTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\DiscountUsageRestrictionTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\DiscountUsageMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeStatusTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeMethodTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Notifications\EmailEventTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Notifications\EmailEventMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\NameSuffixTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\NamePrefixTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\VisitorMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\PasswordResetLinkMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerTagMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerReferralMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerChargeOptionMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\TierShipmentMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\TierPriceMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\SubscriptionChoiceTierPriceCombinationMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\SubscriptionChoiceMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\ProductReviewMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\DisplayProductMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\CategoryMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\BrandMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\AddressMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Tag.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionStatusType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionPeriodType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionPeriod.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionInstance.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\Subscription.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\PendingSubscriptionChange.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\TaxRule.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\SystemSetting.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\StateProvinceType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\Referral.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\PromoCode.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\DiscountApplicabilityType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\DiscountAmountType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\Discount.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralPlan.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralCouponRequestStatusType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralCouponRequest.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferral.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\Partner.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\SubscriptionOrderItemType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\SubscriptionOrderItem.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\StripeCustomerChargeOption.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\StripeCharge.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ShoppingCartItem.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderStatusType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderItem.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderChargeStatusType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\Order.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\DiscountUsageRestrictionType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\DiscountUsage.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeStatusType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeMethodType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\Charge.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Notifications\EmailEventType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Notifications\EmailEvent.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\NameSuffixType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\NamePrefixType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\Visitor.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\PasswordResetLink.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerTag.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerReferral.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerChargeOption.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\Customer.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\TierShipment.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\TierPrice.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\SubscriptionChoiceTierPriceCombination.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\SubscriptionChoice.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\ProductReview.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\DisplayProduct.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\Category.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\Brand.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Address.auto.cs
