// Generated helper templates
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Subscriptions\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Settings\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Promotions\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Partners\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Orders\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Notifications\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Membership\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Customers\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Catalog\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.DataService\_auto\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Subscriptions\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Settings\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Promotions\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Partners\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Orders\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Notifications\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Membership\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Customers\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Catalog\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Subscriptions\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Settings\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Promotions\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Partners\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Notifications\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Membership\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Customers\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Catalog\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Settings\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Promotions\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Partners\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Notifications\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Membership\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Customers\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Notifications\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\AppTransform.txt4
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\AppTransform.txt4
// Generated items
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\TagTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Subscriptions\SubscriptionPeriodTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Subscriptions\SubscriptionInstanceTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Subscriptions\SubscriptionTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Subscriptions\PendingSubscriptionChangeTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Settings\TaxRuleTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Settings\SystemSettingTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Promotions\ReferralTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Promotions\PromoCodeTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Promotions\DiscountTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Partners\PartnerReferralPlanTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Partners\PartnerReferralCouponRequestTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Partners\PartnerReferralTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Partners\PartnerTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Orders\SubscriptionOrderItemTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Orders\StripeCustomerChargeOptionTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Orders\StripeChargeTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Orders\ShoppingCartItemTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Orders\OrderItemTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Orders\OrderTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Orders\DiscountUsageTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Orders\ChargeTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Notifications\EmailEventTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Membership\VisitorTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Membership\PasswordResetLinkTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Customers\CustomerTagTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Customers\CustomerReferralTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Customers\CustomerChargeOptionTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Customers\CustomerTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Catalog\TierShipmentTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Catalog\TierPriceTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Catalog\SubscriptionChoiceTierPriceCombinationTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Catalog\SubscriptionChoiceTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Catalog\ProductReviewTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Catalog\DisplayProductTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Catalog\CategoryTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Catalog\BrandTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\AddressTestsStrategy.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\TagEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Subscriptions\SubscriptionPeriodEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Subscriptions\SubscriptionInstanceEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Subscriptions\SubscriptionEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Subscriptions\PendingSubscriptionChangeEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Settings\TaxRuleEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Settings\SystemSettingEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Promotions\ReferralEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Promotions\PromoCodeEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Promotions\DiscountEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Partners\PartnerReferralPlanEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Partners\PartnerReferralCouponRequestEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Partners\PartnerReferralEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Partners\PartnerEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Orders\SubscriptionOrderItemEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Orders\StripeCustomerChargeOptionEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Orders\StripeChargeEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Orders\ShoppingCartItemEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Orders\OrderItemEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Orders\OrderEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Orders\DiscountUsageEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Orders\ChargeEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Notifications\EmailEventEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Membership\VisitorEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Membership\PasswordResetLinkEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Customers\CustomerTagEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Customers\CustomerReferralEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Customers\CustomerChargeOptionEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Customers\CustomerEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Catalog\TierShipmentEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Catalog\TierPriceEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Catalog\SubscriptionChoiceTierPriceCombinationEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Catalog\SubscriptionChoiceEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Catalog\ProductReviewEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Catalog\DisplayProductEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Catalog\CategoryEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\Catalog\BrandEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.Testing\_auto\AddressEntityWrapper.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Tests.DataService\_auto\DataServicesProvider.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\CommerceDataContext.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\TagValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Subscriptions\SubscriptionPeriodValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Subscriptions\SubscriptionInstanceValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Subscriptions\SubscriptionValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Subscriptions\PendingSubscriptionChangeValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Settings\TaxRuleValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Settings\SystemSettingValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Promotions\ReferralValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Promotions\PromoCodeValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Promotions\DiscountValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Partners\PartnerRegistrationRequestValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Partners\PartnerReferralPlanValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Partners\PartnerReferralCouponRequestValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Partners\PartnerReferralValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Partners\PartnerValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Orders\StripeCustomerChargeOptionValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Orders\StripeChargeValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Orders\ShoppingCartItemValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Orders\OrderValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Orders\DiscountUsageValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Orders\ChargeValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Notifications\EmailEventValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Membership\VisitorValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Membership\UserRegistrationRequestBaseValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Membership\SupportUserRegistrationRequestValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Membership\ResetLostPasswordRequestValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Membership\PasswordResetLinkValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Membership\LoginRequestValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Customers\CustomerTagValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Customers\CustomerRegistrationRequestValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Customers\CustomerReferralValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Customers\CustomerChargeOptionValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Customers\CustomerValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Catalog\TierShipmentValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Catalog\TierPriceValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Catalog\SubscriptionChoiceTierPriceCombinationValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Catalog\SubscriptionChoiceValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Catalog\ProductReviewValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Catalog\DisplayProductValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Catalog\CategoryValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\Catalog\BrandValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Validation\AddressValidator.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\TagService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Subscriptions\SubscriptionStatusTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Subscriptions\SubscriptionPeriodTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Subscriptions\SubscriptionPeriodService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Subscriptions\SubscriptionInstanceService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Subscriptions\SubscriptionService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Subscriptions\PendingSubscriptionChangeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Settings\TaxRuleService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Settings\SystemSettingService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Settings\StateProvinceTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Promotions\ReferralService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Promotions\PromoCodeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Promotions\DiscountApplicabilityTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Promotions\DiscountAmountTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Promotions\DiscountService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Partners\PartnerReferralPlanService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Partners\PartnerReferralCouponRequestStatusTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Partners\PartnerReferralCouponRequestService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Partners\PartnerReferralService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Partners\PartnerService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\SubscriptionOrderItemTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\SubscriptionOrderItemService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\StripeCustomerChargeOptionService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\StripeChargeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\ShoppingCartItemService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\OrderStatusTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\OrderItemService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\OrderChargeStatusTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\OrderService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\DiscountUsageRestrictionTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\DiscountUsageService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\ChargeTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\ChargeStatusTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\ChargeMethodTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\ChargeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Notifications\EmailEventTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Notifications\EmailEventService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\NameSuffixTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\NamePrefixTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Membership\VisitorService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Membership\PasswordResetLinkService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Customers\CustomerTagService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Customers\CustomerReferralService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Customers\CustomerChargeOptionService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Customers\CustomerService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Catalog\TierShipmentService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Catalog\TierPriceService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Catalog\SubscriptionChoiceTierPriceCombinationService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Catalog\SubscriptionChoiceService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Catalog\ProductReviewService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Catalog\DisplayProductService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Catalog\CategoryService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Catalog\BrandService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\AddressService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\ITagService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Subscriptions\ISubscriptionStatusTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Subscriptions\ISubscriptionPeriodTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Subscriptions\ISubscriptionPeriodService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Subscriptions\ISubscriptionInstanceService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Subscriptions\ISubscriptionService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Subscriptions\IPendingSubscriptionChangeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Settings\ITaxRuleService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Settings\ISystemSettingService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Settings\IStateProvinceTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Promotions\IReferralService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Promotions\IPromoCodeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Promotions\IDiscountApplicabilityTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Promotions\IDiscountAmountTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Promotions\IDiscountService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Partners\IPartnerReferralPlanService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Partners\IPartnerReferralCouponRequestStatusTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Partners\IPartnerReferralCouponRequestService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Partners\IPartnerReferralService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Partners\IPartnerService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\ISubscriptionOrderItemTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\ISubscriptionOrderItemService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\IStripeCustomerChargeOptionService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\IStripeChargeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\IShoppingCartItemService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\IOrderStatusTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\IOrderItemService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\IOrderChargeStatusTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\IOrderService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\IDiscountUsageRestrictionTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\IDiscountUsageService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\IChargeTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\IChargeStatusTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\IChargeMethodTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Orders\IChargeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Notifications\IEmailEventTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Notifications\IEmailEventService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\INameSuffixTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\INamePrefixTypeService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Membership\IVisitorService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Membership\IPasswordResetLinkService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Customers\ICustomerTagService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Customers\ICustomerReferralService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Customers\ICustomerChargeOptionService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Customers\ICustomerService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Catalog\ITierShipmentService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Catalog\ITierPriceService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Catalog\ISubscriptionChoiceTierPriceCombinationService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Catalog\ISubscriptionChoiceService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Catalog\IProductReviewService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Catalog\IDisplayProductService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Catalog\ICategoryService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\Catalog\IBrandService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Service\_auto\IAddressService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\TagMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\SubscriptionStatusTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\SubscriptionPeriodTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\SubscriptionPeriodMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\SubscriptionInstanceMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\SubscriptionMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\PendingSubscriptionChangeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\TaxRuleMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\SystemSettingMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\StateProvinceTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\ReferralMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\PromoCodeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\DiscountApplicabilityTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\DiscountAmountTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\DiscountMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\PartnerReferralPlanMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\PartnerReferralCouponRequestStatusTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\PartnerReferralCouponRequestMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\PartnerReferralMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\PartnerMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\SubscriptionOrderItemTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\SubscriptionOrderItemMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\StripeCustomerChargeOptionMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\StripeChargeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\ShoppingCartItemMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\OrderStatusTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\OrderItemMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\OrderChargeStatusTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\OrderMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\DiscountUsageRestrictionTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\DiscountUsageMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\ChargeTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\ChargeStatusTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\ChargeMethodTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\ChargeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\EmailEventTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\EmailEventMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\NameSuffixTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\NamePrefixTypeMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\VisitorMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\PasswordResetLinkMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\CustomerTagMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\CustomerReferralMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\CustomerChargeOptionMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\CustomerMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\TierShipmentMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\TierPriceMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\SubscriptionChoiceTierPriceCombinationMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\SubscriptionChoiceMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\ProductReviewMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\DisplayProductMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\CategoryMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\BrandMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Mapping\AddressMapping.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\CommerceDataContext.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\TagDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\SubscriptionStatusTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\SubscriptionPeriodTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\SubscriptionPeriodDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\SubscriptionInstanceDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\SubscriptionDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\PendingSubscriptionChangeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Settings\TaxRuleDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Settings\SystemSettingDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Settings\StateProvinceTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Promotions\ReferralDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Promotions\PromoCodeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Promotions\DiscountApplicabilityTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Promotions\DiscountAmountTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Promotions\DiscountDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Partners\PartnerReferralPlanDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Partners\PartnerReferralCouponRequestStatusTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Partners\PartnerReferralCouponRequestDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Partners\PartnerReferralDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Partners\PartnerDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\SubscriptionOrderItemTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\SubscriptionOrderItemDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\StripeCustomerChargeOptionDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\StripeChargeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\ShoppingCartItemDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\OrderStatusTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\OrderItemDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\OrderChargeStatusTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\OrderDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\DiscountUsageRestrictionTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\DiscountUsageDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\ChargeTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\ChargeStatusTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\ChargeMethodTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\ChargeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Notifications\EmailEventTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Notifications\EmailEventDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\NameSuffixTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\NamePrefixTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Membership\VisitorDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Membership\PasswordResetLinkDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Customers\CustomerTagDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Customers\CustomerReferralDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Customers\CustomerChargeOptionDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Customers\CustomerDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\TierShipmentDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\TierPriceDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\SubscriptionChoiceTierPriceCombinationDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\SubscriptionChoiceDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\ProductReviewDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\DisplayProductDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\CategoryDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\BrandDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\AddressDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\ITagDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\ISubscriptionStatusTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\ISubscriptionPeriodTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\ISubscriptionPeriodDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\ISubscriptionInstanceDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\ISubscriptionDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Subscriptions\IPendingSubscriptionChangeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Settings\ITaxRuleDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Settings\ISystemSettingDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Settings\IStateProvinceTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Promotions\IReferralDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Promotions\IPromoCodeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Promotions\IDiscountApplicabilityTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Promotions\IDiscountAmountTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Promotions\IDiscountDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Partners\IPartnerReferralPlanDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Partners\IPartnerReferralCouponRequestStatusTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Partners\IPartnerReferralCouponRequestDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Partners\IPartnerReferralDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Partners\IPartnerDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\ISubscriptionOrderItemTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\ISubscriptionOrderItemDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IStripeCustomerChargeOptionDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IStripeChargeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IShoppingCartItemDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IOrderStatusTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IOrderItemDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IOrderChargeStatusTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IOrderDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IDiscountUsageRestrictionTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IDiscountUsageDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IChargeTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IChargeStatusTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IChargeMethodTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Orders\IChargeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Notifications\IEmailEventTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Notifications\IEmailEventDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\INameSuffixTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\INamePrefixTypeDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Membership\IVisitorDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Membership\IPasswordResetLinkDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Customers\ICustomerTagDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Customers\ICustomerReferralDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Customers\ICustomerChargeOptionDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Customers\ICustomerDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\ITierShipmentDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\ITierPriceDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\ISubscriptionChoiceTierPriceCombinationDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\ISubscriptionChoiceDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\IProductReviewDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\IDisplayProductDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\ICategoryDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\Catalog\IBrandDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.DataService\_auto\IAddressDataService.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionStatusTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionPeriodTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\StateProvinceTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\DiscountApplicabilityTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\DiscountAmountTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralCouponRequestStatusTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\SubscriptionOrderItemTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderStatusTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderChargeStatusTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\DiscountUsageRestrictionTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeStatusTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeMethodTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Notifications\EmailEventTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\NameSuffixTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\NamePrefixTypeEnum.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\TagMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionStatusTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionPeriodTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionPeriodMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionInstanceMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\PendingSubscriptionChangeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\TaxRuleMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\SystemSettingMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\StateProvinceTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\ReferralMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\PromoCodeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\DiscountApplicabilityTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\DiscountAmountTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\DiscountMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerRegistrationRequestMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralPlanMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralCouponRequestStatusTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralCouponRequestMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\SubscriptionOrderItemTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\SubscriptionOrderItemMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\StripeCustomerChargeOptionMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\StripeChargeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ShoppingCartItemMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderStatusTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderItemMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderChargeStatusTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\DiscountUsageRestrictionTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\DiscountUsageMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeStatusTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeMethodTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Notifications\EmailEventTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Notifications\EmailEventMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\NameSuffixTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\NamePrefixTypeMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\VisitorMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\UserRegistrationRequestBaseMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\SupportUserRegistrationRequestMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\ResetLostPasswordRequestMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\PasswordResetLinkMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\LoginRequestMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerTagMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerRegistrationRequestMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerReferralMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerChargeOptionMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\TierShipmentMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\TierPriceMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\SubscriptionChoiceTierPriceCombinationMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\SubscriptionChoiceMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\ProductReviewMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\DisplayProductMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\CategoryMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\BrandMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\AddressMetadata.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Tag.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionStatusType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionPeriodType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionPeriod.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\SubscriptionInstance.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\Subscription.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Subscriptions\PendingSubscriptionChange.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\TaxRule.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\SystemSetting.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Settings\StateProvinceType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\Referral.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\PromoCode.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\DiscountApplicabilityType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\DiscountAmountType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Promotions\Discount.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerRegistrationRequest.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralPlan.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralCouponRequestStatusType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferralCouponRequest.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\PartnerReferral.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Partners\Partner.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\SubscriptionOrderItemType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\SubscriptionOrderItem.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\StripeCustomerChargeOption.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\StripeCharge.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ShoppingCartItem.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderStatusType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderItem.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\OrderChargeStatusType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\Order.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\DiscountUsageRestrictionType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\DiscountUsage.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeStatusType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\ChargeMethodType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Orders\Charge.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Notifications\EmailEventType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Notifications\EmailEvent.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\NameSuffixType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\NamePrefixType.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\Visitor.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\UserRegistrationRequestBase.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\SupportUserRegistrationRequest.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\ResetLostPasswordRequest.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\PasswordResetLink.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Membership\LoginRequest.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerTag.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerRegistrationRequest.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerReferral.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\CustomerChargeOption.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Customers\Customer.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\TierShipment.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\TierPrice.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\SubscriptionChoiceTierPriceCombination.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\SubscriptionChoice.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\ProductReview.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\DisplayProduct.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\Category.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Catalog\Brand.auto.cs
// E:\projects\ZAppEngine\Zirpl.Examples.CodeGeneration.VS2013.Commerce.Model\_auto\Address.auto.cs
