// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Zirpl.AppEngine.CodeGeneration.Templates
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Reflection;
    using System.Linq;
    using Zirpl.AppEngine.CodeGeneration;
    using Zirpl.AppEngine.CodeGeneration.ConfigModel;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class ModelTemplate : ModelTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 15 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"

	//this.TemplateHelper = new Zirpl.AppEngine.CodeGeneration.TemplateHelper(this);
// Generate Model classes
//
foreach (DomainType domainType in this.TemplateHelper.DomainTypeFilters.DomainTypesToGenerateModelFor)
{
	this.TemplateHelper.StartModelFile(domainType);
		

            
            #line default
            #line hidden
            this.Write("using System;\r\nusing System.Collections;\r\nusing System.Collections.Generic;\r\nusin" +
                    "g Zirpl.AppEngine.Model;\r\n\r\nnamespace ");
            
            #line 29 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TemplateHelper.NamingProvider.GetModelNamespace(domainType)));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public");
            
            #line 31 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(domainType.IsAbstract ? " abstract" : ""));
            
            #line default
            #line hidden
            this.Write(" partial class ");
            
            #line 31 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(domainType.Name));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 31 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TemplateHelper.TypeProvider.GetModelBaseClass(domainType)));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n");
            
            #line 33 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"

	if (domainType.Properties != null)
	{
		// grab all the collection properties now so we
		// can add initializers in the Constructor
		//
		var collectionProperties = from p in domainType.Properties
									where p.IsCollection
									select p;
		if (collectionProperties.Count() > 0)
		{

            
            #line default
            #line hidden
            this.Write("\t\tpublic ");
            
            #line 45 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(domainType.Name));
            
            #line default
            #line hidden
            this.Write("()\r\n\t\t{\r\n");
            
            #line 47 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"

			foreach (var collectionProperty in collectionProperties)
			{

            
            #line default
            #line hidden
            this.Write("\t\t\tif (this.");
            
            #line 51 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(collectionProperty.Name));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n\t\t\t{\r\n\t\t\t\tthis.");
            
            #line 53 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(collectionProperty.Name));
            
            #line default
            #line hidden
            this.Write(" = new List<");
            
            #line 53 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(collectionProperty.CollectionOfType));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t\t}\r\n");
            
            #line 55 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"

			}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n");
            
            #line 60 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"

		}

		// now go through ALL p
		foreach (var property in domainType.Properties)
		{
			if (property.IsCollection)
			{

            
            #line default
            #line hidden
            this.Write("\t\tpublic virtual IList<");
            
            #line 69 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.CollectionOfType));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 69 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 70 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"

			}
			else
			{
				string propertyType = property.Type;
				propertyType = propertyType.ToLowerInvariant() == "currency" ? "decimal" : propertyType;
				if (!property.IsRequired
					&& (propertyType.ToLowerInvariant() == "datetime"
						||propertyType.ToLowerInvariant() == "byte"
						||propertyType.ToLowerInvariant() == "bool"
						||propertyType.ToLowerInvariant() == "int"
						||propertyType.ToLowerInvariant() == "decimal"
						||propertyType.ToLowerInvariant() == "double"
						||propertyType.ToLowerInvariant() == "guid"))
                {
					propertyType += "?";
                }

            
            #line default
            #line hidden
            this.Write("\t\tpublic ");
            
            #line 88 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((domainType.IsDictionary && property.Name == "Name") ? "override" : "virtual")));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 88 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 88 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 89 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"

				if (property.IsRelationship
					&& property.GenerateIdProperty)
				{
					var relationshipModel = this.TemplateHelper.DomainTypeFilters.GetDomainTypeByFullTypeName(property.Type);
					string relationshipIdTypeString = !String.IsNullOrEmpty(relationshipModel.IdTypeOverride)
													? relationshipModel.IdTypeOverride
													: (relationshipModel.IsDictionary ? "byte" : "int");
					relationshipIdTypeString += (property.IsRequired ? "" : "?");
					

            
            #line default
            #line hidden
            this.Write("\t\tpublic virtual ");
            
            #line 100 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relationshipIdTypeString));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 100 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("Id { get; set; }\r\n");
            
            #line 101 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"

				}
			}
		}
	}

            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n\r\n");
            
            #line 110 "E:\projects\ZAppEngine\Zirpl.AppEngine.CodeGeneration.VS2013\Templates\ModelTemplate.tt"

}

//this.TemplateHelper.End();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        /// <summary>
        /// The current host for the text templating engine
        /// </summary>
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class ModelTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
